require "base.launch"
require "base.options"
require "base.autocmds"
require "base.keymaps"

spec "user.whichkey"
spec "user.devicons"
spec "user.diffview"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.neo-tree"
spec "user.mini-bufremove"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.neotest"
spec "user.autopairs"
spec "user.lazygit"
spec "user.alpha"
spec "user.indentline"
spec "user.toggleterm"
spec "user.bufferline"
spec "user.edgy"
spec "user.noice"
spec "user.conform"
spec "user.trouble"
spec "user.todo-comments"
spec "user.typescript-tools"
spec "user.neural"

-- Colorschemes
spec "colorschemes.catppuccin"
-- spec "colorschemes.embark"
-- spec "colorschemes.everforest"
-- spec "colorschemes.kanagawa"
-- spec "colorschemes.pastelnight"
-- spec "colorschemes.pastelnight"
-- spec "colorschemes.rose-pine"

-- Extras
spec "user.extras.copilot"
spec "user.extras.copilotchat"
spec "user.extras.chatgpt"
spec "user.extras.oil"
spec "user.extras.ufo"
spec "user.extras.fidget"
spec "user.extras.neoscroll"
spec "user.extras.neotab"
spec "user.extras.colorizer"

require "base.lazy"
